ECC_params = open("ECC_params.jl","w")
write(ECC_params, "# Input data for camera calibration - CACO field data 2022 \n \n") # From: https://shuvomoy.github.io/blogs/posts/Saving_data_files_julia/
write(ECC_params, "GCPnames_us = ")
show(ECC_params, GCPnames)
write(ECC_params, "; \n \n")
write(ECC_params, "GCPuv_us = ")
show(ECC_params, GCPuv_us)
write(ECC_params, "; \n \n")
# write(ECC_params, "GCPuv_fix_ds = ")
# show(ECC_params, GCPuv_fix_ds)
# write(ECC_params, "; \n \n")
write(ECC_params, "GCPxyz_us = ")
show(ECC_params, GCPxyz_us)
write(ECC_params, "; \n \n")
write(ECC_params, "GCPlla_us = ")
show(ECC_params, GCPlla_us)
write(ECC_params, "; \n \n")
write(ECC_params, "GCPzguess_us = guessed vertical location of GCPs due to poor vertical accuracy from intertialsense antenna; \n")
write(ECC_params, "GCPzguess_us = ")
show(ECC_params, GCPzg_us)
write(ECC_params, "; \n \n")
# write(ECC_params, "GCPxyz_fix_ds = ")
# show(ECC_params, GCPxyz_fix_ds)
# write(ECC_params, "; \n \n")
write(ECC_params, "ECPs_us = ")
show(ECC_params, ECPs_us)
write(ECC_params, "; \n \n")
# write(ECC_params, "ECPs_ds = ")
# show(ECC_params, ECPs_ds)
# write(ECC_params, "; \n \n")
write(ECC_params, "bo_tape_us = physical (xy) location of tape strip in UTM calculated from recorded antenna location at farthest strip of board away from deck (elevation of all should be z=0); \n")
write(ECC_params, "bo1_tape_us = ")
show(ECC_params, bo1_tape_us)
write(ECC_params, "; \n \n")
write(ECC_params, "bo2_tape_us = ")
show(ECC_params, bo2_tape_us)
write(ECC_params, "; \n \n")
write(ECC_params, "bo_uv_us = pixel (uv) location of tape strip in image; \n")
write(ECC_params, "bo1_uv_us = ")
show(ECC_params, bo1_uv_us)
write(ECC_params, "; \n \n")
write(ECC_params, "bo2_uv_us = ")
show(ECC_params, bo2_uv_us)
write(ECC_params, "; \n \n")
close(ECC_params)